import Head from 'next/head'
import dynamic from "next/dynamic";

const Login = dynamic(
  () => {
    return import("../components/Login");
  },
  { ssr: false }
);

function Home() {
  return (
    <>
      <Head>
        <title>Restraunt</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Login/>
    </>
  )
}
export default Home
